import pytest
from app.security.crypto import encrypt_credential, decrypt_credential, CryptoError

KEY_HEX = "4571f96ffa2ca77dda67ff1dca99883734dd1033475db8b5f3190849d7949dbe"

def test_encryption_decryption_roundtrip():
    plaintext = "my-secret-password-123"
    
    # 1. Encrypt in Python
    encrypted = encrypt_credential(plaintext, KEY_HEX, key_version=1)
    assert encrypted.startswith("v1:")
    
    parts = encrypted.split(":")
    assert len(parts) == 4
    
    # 2. Decrypt in Python
    decrypted = decrypt_credential(encrypted, KEY_HEX)
    assert decrypted == plaintext

def test_node_compatibility_decryption():
    # Ciphertext generated by Node.js crypto using the same KEY_HEX and plaintext: "my-super-secret-password-123"
    node_ciphertext = "v1:f77a51b965146de776c4a5d44179fc25:55493f4fdd165b5b1add6816f4bd5e67:57488f9a1c7b46967f6fc395c3ba541b1b64e4cac72afea78abe583f"
    
    decrypted = decrypt_credential(node_ciphertext, KEY_HEX)
    assert decrypted == "my-super-secret-password-123"

def test_invalid_parameters():
    with pytest.raises(CryptoError):
        encrypt_credential("", KEY_HEX)
        
    with pytest.raises(CryptoError):
        decrypt_credential("invalid_format", KEY_HEX)
        
    with pytest.raises(CryptoError):
        # Invalid key size (must be 32 bytes/64 hex characters)
        encrypt_credential("hello", "12345")
